### ISSUE TITLE
Python installation fails

### ISSUE THREAD

**Issue by vialcollet** [azavea/ansible-graphite#12]
Hi

When applying this role on one of my debian server I have the following error:

```
TASK [azavea.python : Install Python] ******************************************
fatal: [xxxxx]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'python=2.7.5-5ubuntu3'' failed: E: Version '2.7.5-5ubuntu3' for 'python' was not found\n", "stderr": "E: Version '2.7.5-5ubuntu3' for 'python' was not found\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}
```
Any idea what happens?

Thanks in advance

**Comment by hectcastro** [comment]
Hey @vialcollet,

These roles have mostly been tested on Ubuntu, and despite its similarity to Debian, things like package names suffixes can cause problems. In your case, the role's default Python package version is `2.7.5-5ubuntu3`, which doesn't exist in your Debian package repository.

That said, you should be able to at least get past this error by overriding the `python_version` variable somewhere in your Ansible configuration to whatever package version exists for the `python` package on Debian.

**Comment by hectcastro** [comment]
Closing for now, but feel free to reopen if you aren't able to get this working.
