### ISSUE TITLE
Apache does not listen to the port by default

### ISSUE THREAD

**Issue by georgegeka** [azavea/ansible-graphite#9]
graphite_web_port , should be ensured to be added to the ports that apache is listening to
for example in /etc/apache2/ports.conf
Listen 8080 
should be ensured to present

**Comment by hectcastro** [comment]
The [example project shows](https://github.com/azavea/ansible-graphite/blob/fe04039d6ed3aded16aa5c801a77e4783cefe66a/examples/site.yml#L5) how instruct the `apache2` role to update `ports.conf`. This consists of setting `apache_port` to the same port as `graphite_web_port`.
